### ISSUE TITLE
TR: DS regexes with non-consecutive order generate invalid CRconfig/Snapshot

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#3548]
By ignorance or by maybe by design, I created a CR-config that got rejected from Traffic router. I added a `HOST_REGEXP` with order of "10" which shouldn't have been a problem (there is no default value). 

This created a bunch of null entries added in the CR-Config which Traffic router was unable to parse.

Note: CR-Config rejections are not being relayed back to users in Portal.

```
  "test-ds": {
    "coverageZoneOnly": "false",
    "deepCachingType": "NEVER",
    "domains": [
      "test-ds.wcdn.cox.net"
    ],
    "geolocationProvider": "maxmindGeolocationService",
    "ip6RoutingEnabled": "false",
    "matchsets": [
      {
        "matchlist": [
          {
            "match-type": "HOST",
            "regex": ".*\\.test-ds\\..*"
          }
        ],
        "protocol": "DNS"
      },
++    null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      {
        "matchlist": [
          {
            "match-type": "HOST",
            "regex": "mycname.cdn.cox.net"
          }
        ],
        "protocol": "DNS"
      }
    ],
```

Traffic Router logs:

```
WARN  2019-05-06T12:51:56.861 [New I/O worker #2] com.comcast.cdn.traffic_control.traffic_router.core.monitor.TrafficMonitorWatcher - com.comcast.cdn.traffic_control.traffic_router.core.util.JsonUtilsException: Failed querying JSON for key: protocol
com.comcast.cdn.traffic_control.traffic_router.core.util.JsonUtilsException: Failed querying JSON for key: protocol
        at com.comcast.cdn.traffic_control.traffic_router.core.util.JsonUtils.throwException(JsonUtils.java:131)
        at com.comcast.cdn.traffic_control.traffic_router.core.util.JsonUtils.getString(JsonUtils.java:104)
        at com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler.parseDeliveryServiceConfig(ConfigHandler.java:439)
        at com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler.processConfig(ConfigHandler.java:176)
        at com.comcast.cdn.traffic_control.traffic_router.core.monitor.TrafficMonitorWatcher$2.update(TrafficMonitorWatcher.java:116)
        at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater.updateDatabase(PeriodicResourceUpdater.java:165)
        at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater$UpdateHandler.onCompleted(PeriodicResourceUpdater.java:285)
        at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater$UpdateHandler.onCompleted(PeriodicResourceUpdater.java:256)
        at com.ning.http.client.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:63)
        at com.ning.http.client.providers.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:279)
        at com.ning.http.client.providers.netty.NettyResponseFuture.done(NettyResponseFuture.java:307)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.markAsDone(NettyAsyncHttpProvider.java:1454)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.finishUpdate(NettyAsyncHttpProvider.java:1470)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.access$2600(NettyAsyncHttpProvider.java:158)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2229)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.messageReceived(NettyAsyncHttpProvider.java:1163)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mitchell852** [comment]
@smalenfant - seems like this could be fixed in 4 places:

TR, Crconfig generation/snapshotting, TO API and TP. Although, I think the right thing is maybe to fix it in all 4 areas, at a minimum TR should be more defensive imo.

**Comment by mitchell852** [comment]
marked this as tech debt/bug as this is a bug that can occur because of insufficient TR defensive coding.

**Comment by mitchell852** [comment]
fyi, i updated the issue title to better describe the issue (i.e. this is not specific to Traffic Portal)
