### ISSUE TITLE
Traffic Portal not Open Server Port

### ISSUE THREAD

**Issue by riupie** [apache/trafficcontrol#4120]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Version : 3.1
So I installed Traffic Portal and Traffic Ops on different server. I can install Traffic Ops and running normally. Then I installed Traffic Ops, its status was active in systemctl but it didnt open port 80 or 443. It is like node server not running.

This is my Traffic Portal configuration:

##### /etc/traffic_portal/conf/config.js
```
    // set api 'base_url' to the traffic ops api url (all api calls made from the traffic portal will be proxied to the api base_url)
    api: {
//        base_url: 'https://trafficops.CHANGEME.domain.com/api/'
          base_url: 'https://trafficops.ethernet.id:443/api/'
    }
```

##### /opt/traffic_portal/public/traffic_portal_properties.json
```
  "properties": {
    "name": "Traffic Portal",
    "api": {
      "_comment": "This should have the same value found in /etc/traffic_portal/conf/config.js",
//      "baseUrl": "https://localhost:8444/api/"
        "baseUrl": "https://trafficops.ethernet.id:443"
    }
```
## Expected / new behavior:

It should be running on port 80 or 443.
## Minimal reproduction of the problem with instructions:

I only checked via `netstat -nltp` and there is no `node` service/program running on port 80/443 like in the docker/CIAB version.

**Comment by ocket8888** [comment]
did you check the logs? If you don't have SSL key/certs under `/etc/pki` (default) TP will not start.

**Comment by riupie** [comment]
> did you check the logs? If you don't have SSL key/certs under `/etc/pki` (default) TP will not start.

I generate self-signed SSL by running this command make testcert DAYS=600 in /etc/pki/private (if im not wrong). i dont know how to generate the ca-bundle part.

**Comment by riupie** [comment]
Error from traffic portal log.

```
    at Object.createSecureContext (_tls_common.js:85:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/opt/traffic_portal/server.js:120:29)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
error: Forever detected script exited with code: 1

```

**Comment by ocket8888** [comment]
can you give me the full log? The actual error occurred above that line snippet.

**Comment by riupie** [comment]
There are so many line, so I put some sample only.
```
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Error (native)
    at Object.createSecureContext (_tls_common.js:85:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/opt/traffic_portal/server.js:120:29)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
error: Forever detected script exited with code: 1
error: Script restart attempt #23
_tls_common.js:85
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Error (native)
    at Object.createSecureContext (_tls_common.js:85:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/opt/traffic_portal/server.js:120:29)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
error: Forever detected script exited with code: 1
error: Script restart attempt #24
_tls_common.js:85
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Error (native)
    at Object.createSecureContext (_tls_common.js:85:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/opt/traffic_portal/server.js:120:29)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
error: Forever detected script exited with code: 1
error: Script restart attempt #25
error: Forever detected script was killed by signal: SIGKILL
_tls_common.js:85
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Error (native)
    at Object.createSecureContext (_tls_common.js:85:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/opt/traffic_portal/server.js:120:29)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
_tls_common.js:85
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Error (native)
    at Object.createSecureContext (_tls_common.js:85:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/opt/traffic_portal/server.js:120:29)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
error: Forever detected script exited with code: 1
error: Script restart attempt #2
_tls_common.js:85
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Error (native)
    at Object.createSecureContext (_tls_common.js:85:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/opt/traffic_portal/server.js:120:29)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
error: Forever detected script exited with code: 1
error: Script restart attempt #3
_tls_common.js:85
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Error (native)
    at Object.createSecureContext (_tls_common.js:85:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:49:10)
    at Object.<anonymous> (/opt/traffic_portal/server.js:120:29)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
error: Forever detected script exited with code: 1

```

The last log was produced when I use this config:

```
// this is the config that is consumed by /server.js on traffic portal startup (sudo service traffic_portal start)
module.exports = {
    timeout: '120s',
    useSSL: true, // set to true if you plan to use https (self-signed or trusted certs).
    port: 80, // set to http port
    sslPort: 443, // set to https port
    // if useSSL is true, generate ssl certs and provide the proper locations.
    ssl: {
        key:    '/etc/pki/tls/private/localhost.key',
        cert:   '/etc/pki/tls/certs/localhost.crt',
        ca:     [ '/etc/pki/tls/certs/ca-bundle.crt' ]
```

**Comment by mitchell852** [comment]
try creating an empty ca-bundle.crt

**Comment by ocket8888** [comment]
yeah, my `ca-bundle.crt` is a zero-byte file. and looking at that error, the problem is definitely SSL-related.

**Comment by riupie** [comment]
So.. I should create and empty file and pointing the ca part in config file to that empty file?

**Comment by ocket8888** [comment]
works for me!

**Comment by riupie** [comment]
Ok,  I will try it first.  Btw are there any authentication for communication between service? In my scenario,  between TO and TP?

**Comment by riupie** [comment]
Solved. I dont know what is the error. But I try to install it in new VM with same configuration and it work perfectly.

**Comment by ocket8888** [comment]
That is bizarre. If you ever figure out what the problem was, we'd appreciate it if you could post here for posterity.

In answer to your question:

> _"Btw are there any authentication for communication between service? In my scenario, between TO and TP?"_

No. TP is just a "shell" around TO, it doesn't need to authenticate you because when you log in to TP you're really logging into TO.
