### ISSUE TITLE
Kickstart script broken

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#4285]
## I'm submitting a ...
- bug report

## Traffic Control components affected ...
- tools (`kickstart_create_network_line.py`)

## Current behavior:
There's a bug in the script:
```
  File "./kickstart_create_network_line.py", line 25
    from __future__ import print_function
SyntaxError: from __future__ imports must occur at the beginning of the file
```

## Expected / new behavior:
There shouldn't be a bug in the script

## Minimal reproduction of the problem with instructions:
Run the script

**Comment by ocket8888** [comment]
Also one thing that's not Python3-friendly:
```python traceback
Traceback (most recent call last):
  File "./kickstart_create_network_line.py", line 232, in <module>
    bondable_iface, iface_problems = useable_interfaces(net_devs, nc, iface_speed)
  File "./kickstart_create_network_line.py", line 174, in useable_interfaces
    speeds.sort(reverse=True)
AttributeError: 'dict_keys' object has no attribute 'sort'
```
Works fine in Python2 - though of course we're not supposed to support that anymore.
