### ISSUE TITLE
TR doesn't work with disabled coveragezone

### ISSUE THREAD

**Issue by cheluskin** [apache/trafficcontrol#4808]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [x ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
TR does not start with error **Failed querying JSON for key: coveragezone.polling.url** but Coverage Zone File not enabled in cache group
("localizationMethods":["GEO"] in tm CrConfig)

## Expected / new behavior:

should not give an error when the option is disabled

## Minimal reproduction of the problem with instructions:

TC 4.0.x

## Anything else:
`INFO  2020-06-19T09:38:10.235 [New I/O worker #6] com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler - Entered processConfig
WARN  2020-06-19T09:38:10.238 [New I/O worker #6] com.comcast.cdn.traffic_control.traffic_router.core.monitor.TrafficMonitorWatcher - com.comcast.cdn.traffic_control.traffic_router.core.util.JsonUtilsException: Failed querying JSON for key: coveragezone.polling.url
com.comcast.cdn.traffic_control.traffic_router.core.util.JsonUtilsException: Failed querying JSON for key: coveragezone.polling.url
	at com.comcast.cdn.traffic_control.traffic_router.core.util.JsonUtils.throwException(JsonUtils.java:131)
	at com.comcast.cdn.traffic_control.traffic_router.core.util.JsonUtils.getString(JsonUtils.java:104)
	at com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler.parseCoverageZoneNetworkConfig(ConfigHandler.java:624)
	at com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler.processConfig(ConfigHandler.java:164)
	at com.comcast.cdn.traffic_control.traffic_router.core.monitor.TrafficMonitorWatcher$2.update(TrafficMonitorWatcher.java:116)
	at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater.updateDatabase(PeriodicResourceUpdater.java:166)
	at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater$UpdateHandler.onCompleted(PeriodicResourceUpdater.java:286)
	at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater$UpdateHandler.onCompleted(PeriodicResourceUpdater.java:257)
	at com.ning.http.client.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:63)
	at com.ning.http.client.providers.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:279)
	at com.ning.http.client.providers.netty.NettyResponseFuture.done(NettyResponseFuture.java:307)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.markAsDone(NettyAsyncHttpProvider.java:1454)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.finishUpdate(NettyAsyncHttpProvider.java:1470)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.access$2600(NettyAsyncHttpProvider.java:158)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2211)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.messageReceived(NettyAsyncHttpProvider.java:1163)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
WARN  2020-06-19T09:38:10.239 [New I/O worker #6] com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater - File rejected: /opt/traffic_router/db/cr-config.json
ERROR 2020-06-19T09:38:14.998 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:38:19.999 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:38:24.999 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:38:30.000 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:38:35.000 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:38:40.001 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:38:45.001 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:38:50.001 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:38:55.002 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:39:00.002 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:39:05.003 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!
ERROR 2020-06-19T09:39:10.003 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!`

**Comment by rawlinp** [comment]
I marked this as an RFE rather than a bug since TR is working as designed -- today a coverage zone file is a requirement for TR to run. Although, it doesn't have to be a _real_ coverage zone file -- it could be basically empty and TR should work.
