### ISSUE TITLE
Traffic Ops unit tests Docker container exits on go get

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#4839]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

The Traffic Ops unit tests Docker container exits on `go get` (running at 78e4b005fc).

## Expected / new behavior:

Traffic Ops unit tests Docker container should exit with no errors after running unit tests

## Minimal reproduction of the problem with instructions:

```shell script
docker-compose -f traffic_ops/app/bin/tests/docker-compose.yml up --build
```

**Comment by zrhoffman** [comment]
The Traffic Ops API tests docker container also fails to build now.

```dockerfile
 => ERROR [integration-builder 18/18] RUN CGO_ENABLED=0 go test -c ./v3* -ldflags="-w -s" -o traffic_ops_v3_integration_test                                                                                                              0.8s
------
 > [integration-builder 18/18] RUN CGO_ENABLED=0 go test -c ./v3* -ldflags="-w -s" -o traffic_ops_v3_integration_test:
#31 0.681 FAIL  github.com/apache/trafficcontrol/traffic_ops/testing/api/v3 [setup failed]
#31 0.681 # github.com/apache/trafficcontrol/traffic_ops/testing/api/v3
#31 0.681 package github.com/apache/trafficcontrol/traffic_ops/testing/api/v3 (test)
#31 0.681       imports github.com/apache/trafficcontrol/traffic_ops/client
#31 0.681       imports github.com/apache/trafficcontrol/grove/web: cannot find package "github.com/apache/trafficcontrol/grove/web" in any of:
#31 0.681       /go/src/github.com/apache/trafficcontrol/traffic_ops/vendor/github.com/apache/trafficcontrol/grove/web (vendor tree)
#31 0.681       /go/src/github.com/apache/trafficcontrol/vendor/github.com/apache/trafficcontrol/grove/web
#31 0.681       /usr/local/go/src/github.com/apache/trafficcontrol/grove/web (from $GOROOT)
#31 0.681       /go/src/github.com/apache/trafficcontrol/grove/web (from $GOPATH)
#31 0.683 FAIL
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c CGO_ENABLED=0 go test -c ./v3* -ldflags="-w -s" -o traffic_ops_v3_integration_test]: runc did not terminate sucessfully
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.26.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1078, in up
    to_attach = up(False)
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1059, in up
    return self.project.up(
  File "/usr/lib/python3.8/site-packages/compose/project.py", line 548, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 367, in ensure_image_exists
    self.build(cli=cli)
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 1110, in build
    all_events = list(stream_output(build_output, output_stream))
  File "/usr/lib/python3.8/site-packages/compose/progress_stream.py", line 25, in stream_output
    for event in utils.json_stream(output):
  File "/usr/lib/python3.8/site-packages/compose/utils.py", line 61, in split_buffer
    for data in stream_as_text(stream):
  File "/usr/lib/python3.8/site-packages/compose/utils.py", line 37, in stream_as_text
    for data in stream:
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 1819, in build
    with open(iidfile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5cepmutd'
```
