### ISSUE TITLE
TP Tests GHA: SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 89

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5640]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  CI tests (Traffic Portal End-to-End tests GitHub Action)

## Current behavior:

The *TP E2E Tests* GitHub Actions workflow fails:

```javascript
[21:15:34] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 89
Current browser version is 88.0.4324.182 with binary path /usr/bin/google-chrome
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'fv-az182-967', ip: '10.1.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1040-azure', java.version: '11.0.10'
Driver info: driver.version: unknown
remote stacktrace: #0 0x56519af252b9 <unknown>

    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:626:16)
    at Local.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:195:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[21:15:34] E/launcher - Process exited with error code 199
```

## Expected behavior:

The *TP E2E Tests* GitHub Actions workflow should pass.

## Minimal reproduction of the problem with instructions:

1. Commit a change that triggers the *TP E2E Tests* workflow
  ```shell
  touch traffic-portal/a-change
  git add traffic-portal/a-change
  git commit -m 'A change'
  git push your-fork HEAD:a-branch
  ```

2. Go to `https://github.com/<your-fork>/trafficcontrol/actions/workflows/tp.e2e.tests.yml` for the result and check the logs

**Comment by zrhoffman** [comment]
When running with `set -o xtrace`:
https://github.com/apache/trafficcontrol/blob/c52ba7baf4b112b45b1958869ffe706a6a8e8376/.github/actions/tp-e2e-tests/entrypoint.sh#L150-L152
yields

> ```shell
> 2021-03-12T21:55:48.4996827Z + CHROME_VER=89.0.4389.82
> 2021-03-12T21:55:48.4999005Z + sudo webdriver-manager update --gecko false --versions.chrome LATEST_RELEASE_89.0.4389.82
> ```

But later:
> ```shell
> 2021-03-12T21:57:18.8295139Z Current browser version is 88.0.4324.182 with binary path /usr/bin/google-chrome
> ```

So the Chrome version on disk in the Docker container is newer than the Chrome version running in the Docker container (Chrome has updated itself?). This should be fixable by creating a new container to check the version instead of `exec`ing into the existing one.

**Comment by zrhoffman** [comment]
> So the Chrome version on disk in the Docker container is newer than the Chrome version running in the Docker container (Chrome has updated itself?). This should be fixable by creating a new container to check the version instead of `exec`ing into the existing one.

Nope that's not it. Chrome is versioned *89.0.4389.82* everywhere in `selenium/node-chrome@sha256:ce2b1d6f50d1e3a65da70b9ae2d1a1e235239bd553deeb26d2255b4cacc4be6a`. There's no trace of `88.0.4324.182` in the image.

**Comment by ocket8888** [comment]
I've noticed this occurring with Protractor tests when new Chrome versions are released. I don't think I ever found a solution, though the problems appear to be transient.

**Comment by zrhoffman** [comment]
Closing for now since this intermittent issue is no longer occurring. We can consider re-opening the next time Chrome is updated if this happens again.
