### ISSUE TITLE
TR dnschallenges: exception when regexp doesn't match the xmlId

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#6093]
## This Bug Report affects these Traffic Control components:

- Traffic Router

## Current behavior:

Exception when DS regexp doesn't match the xmlId. Certificate not created.

```
WARN  2021-08-10T15:37:49.750 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.ds.LetsEncryptDnsChallengeWatcher - Failed updating dns challenge txt record with data from https://${toHostname}/api/2.0/letsencrypt/dnsrecords/:
java.lang.NullPointerException
	at com.comcast.cdn.traffic_control.traffic_router.core.ds.LetsEncryptDnsChallengeWatcher.updateStaticEntries(LetsEncryptDnsChallengeWatcher.java:152)
	at com.comcast.cdn.traffic_control.traffic_router.core.ds.LetsEncryptDnsChallengeWatcher.lambda$useData$0(LetsEncryptDnsChallengeWatcher.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.comcast.cdn.traffic_control.traffic_router.core.ds.LetsEncryptDnsChallengeWatcher.useData(LetsEncryptDnsChallengeWatcher.java:59)
	at com.comcast.cdn.traffic_control.traffic_router.core.util.AbstractResourceWatcher.loadDatabase(AbstractResourceWatcher.java:108)
	at com.comcast.cdn.traffic_control.traffic_router.core.loc.AbstractServiceUpdater.updateDatabase(AbstractServiceUpdater.java:117)
	at com.comcast.cdn.traffic_control.traffic_router.core.loc.AbstractServiceUpdater$1.run(AbstractServiceUpdater.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Expected behavior:

Let's Encrypt certificate created

## Steps to reproduce:

- Create a new DS
- Change the Regexp so it doesn't match the xmlId
- Snapshot, verify DS is working
- Add a Let's Encrypt SSL certificate
- Watch for Exceptions in the log

**Comment by mitchell852** [comment]
@smalenfant can you make sure to add component labels as well to your issues?
