### ISSUE TITLE
Read the Docs: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#7500]
## This Bug Report affects these Traffic Control components:

- Documentation

## Current behavior:

The Read the Docs CI to build the documentation is broken. From https://readthedocs.org/projects/traffic-control-cdn/builds/20564986/ :

```shell
 Running Sphinx v4.0.3
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/traffic-control-cdn/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 420, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/traffic-control-cdn/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/traffic-control-cdn/envs/latest/lib/python3.7/site-packages/sphinx/builders/linkcheck.py", line 28, in <module>
    from requests import Response
  File "/home/docs/checkouts/readthedocs.org/user_builds/traffic-control-cdn/envs/latest/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/docs/checkouts/readthedocs.org/user_builds/traffic-control-cdn/envs/latest/lib/python3.7/site-packages/urllib3/__init__.py", line 39, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/traffic-control-cdn/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/traffic-control-cdn/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 239, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/traffic-control-cdn/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 400, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/traffic-control-cdn/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 424, in load_extension
    err) from err
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)

Extension error:
Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)
```

## Expected behavior:

The Read the Docs CI should pass.

## Steps to reproduce:

1. Go to https://readthedocs.org/projects/traffic-control-cdn/builds/
2. See the last run was 2023-05-08
3. See the last successful run was 2023-05-03

**Comment by zrhoffman** [comment]
They updated the readthedocs image and our docs build successfully again, can no longer reproduce.
