### ISSUE TITLE
[TC-295] Invalid DS regex causes nasty exception and unexpected results Github Issue #514

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#911]
<p>If a host regex (probably others) is specified as a plain string, rather than a real regex (e.g.: test vs ..mydeliveryservice..), the following exception occurs in Traffic Router, and the user would have to be watching the logs to see that something went wrong. Additionally, it is not clear why the failure occurred.</p>

<p>Improve TO in general such that the regex is clearly defined (documented?) and potentially checked so that it doesn't get added to the CRConfig until it is what we expect to see. Additionally, discuss whether we want to support specific strings (e.g.: test) instead of a full regex. Doing so seems to be counter to the intent of the regex in the first place, so I do not think that this is a viable option at this time.</p>

<p>WARN 2015-09-01T14:25:07.237 <a href="#1">New I/O worker #1</a> com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater - 1 java.lang.ArrayIndexOutOfBoundsException: 1 at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.populateZoneMap(ZoneManager.java:311) at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.generateZones(ZoneManager.java:132)</p>

Author: Dewayne Richardson
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-295">https://issues.apache.org/jira/browse/TC-295</a>

**Comment by rawlinp** [comment]
Going to piggyback on this issue because it's along the same lines:
If you _don't_ create a HOST_REGEXP at all in the TO UI (i.e. leave it blank), TO will give you a blank HOST_REGEXP and will not throw any errors when generating the CRConfig. However, Traffic Router will _reject_ the newly snapshotted CRConfig because an exception will occur when parsing it:
```
WARN  2017-08-31T22:54:51.969 [New I/O worker #2] com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater - No match found
java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Matcher.java:536)
        at com.comcast.cdn.traffic_control.traffic_router.core.request.RequestMatcher.<init>(RequestMatcher.java:45)
        at com.comcast.cdn.traffic_control.traffic_router.core.ds.DeliveryServiceMatcher.addMatch(DeliveryServiceMatcher.java:48)
        at com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler.parseDeliveryServiceMatchSets(ConfigHandler.java:420)
        at com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler.processConfig(ConfigHandler.java:192)
        at com.comcast.cdn.traffic_control.traffic_router.core.monitor.TrafficMonitorWatcher$2.update(TrafficMonitorWatcher.java:114)
        at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater.updateDatabase(PeriodicResourceUpdater.java:154)
        at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater$UpdateHandler.onCompleted(PeriodicResourceUpdater.java:260)
        at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater$UpdateHandler.onCompleted(PeriodicResourceUpdater.java:245)
```

**Comment by mitchell852** [comment]
TO UI is going to be deprecated soon so I wouldn't worry about fixing that.

TP (or more specifically the TO API) creates a ds regex of type= HOST_REGEXP with value = ..xml-id.. for you in position zero however, you can change the value of that regex and cause problems so TP probably needs some better validation to ensure the proper format for the ds regex in position zero.
